// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package models

import (
	"context"
)

const addSecret = `-- name: AddSecret :one
INSERT INTO secrets (value) VALUES (?) RETURNING id
`

func (q *Queries) AddSecret(ctx context.Context, value []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, addSecret, value)
	var id int64
	err := row.Scan(&id)
	return id, err
}
